import { AppProvider } from "@/components/providers/AppProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Merriweather_Sans } from "next/font/google";
import { Navbar } from "@/components/navbar/Navbar";

const inter = Merriweather_Sans({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AppProvider>
          <Navbar />

          <main className="container">{children}</main>
        </AppProvider>
      </body>
    </html>
  );
}
